### ISSUE TITLE
can not install kurento-client 

### ISSUE THREAD

**Issue by fadiquader** [Fiware/tutorials.Media-Streams#5]
Thank you for the tutorial.
I have a problem in installing kurento-client
<img width="949" alt="Screen Shot 2019-05-26 at 1 24 38 AM" src="https://user-images.githubusercontent.com/23264052/58372867-f6709880-7f56-11e9-9bc8-d5da42566ca2.png">

After search for a while that some old dependencies depend on an old version of node meanwhile i use node v12, the solution that i've found is to downgrade to an older version, which it's not a practical solution for me.
Do you know which packages to add them in resolution instead?

Thank you in advance.

**Comment by jason-fox** [comment]
Hi @fadiquader 

Your question goes beyond the scope of this introductory tutorial. To get a comprehensive answer to your question, you would be better off posting elsewhere. Either on the Kurento bugs list GitHub Repo or the Kurento support tag on Stack Overflow.

* https://github.com/Kurento/bugtracker
* https://stackoverflow.com/questions/tagged/kurento

AFAIK both of these are monitored by the Kurento team themselves.

The tutorial is using docker and automatically uses **Node 8** as a default since (at the time of writing) this was the node  LTS version. Maybe you could dockerize your environment to do the same? I  would assume Node 12 support should be on the Kurento roadmap since it would be the active support version from [November 2019](https://nodejs.org/en/about/releases/)
